version: '2.6'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: tikzed/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: tikzed/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    image: tikzed/foodgram_gateway
    env_file: .env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    ports:
      - 8000:80
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  postgres_data:
  redoc: