MAX_LENGTH = 200
MAX_LENGTH_USER = 150
MAX_LENGTH_EMAIL = 200
MIN_COOKING_TIME_AMOUNT = 1
MAX_COOKING_TIME_AMOUNT = 32000
MASSAGE_E_COOK = 'Неправильное время'
MASSAGE_E_AMOUNT = 'Некоректное кол-во'
PAG_LIMIT = 6
